name: SimpleStacker
version: 1.0-SNAPSHOT
main: net.stacking.simpleStacker.SimpleStacker
api-version: '1.21'
author: Infamous Dragon
description: Stack items beyond normal limits

commands:
  stack:
    description: Stack all items in your inventory
    usage: /stack
    permission: simplestacker.use
    permission-message: "§d§lYou don't have permission to use this command!"

permissions:
  simplestacker.use:
    description: Allows players to use /stack command
    default: op
