# SimpleStacker Configuration
# EVERY item that normally stacks less than 64 is now 64!

items:
  # Food (normally 16)
  EGG: 64
  SNOWBALL: 64
  ENDER_PEARL: 64

  # Potions (normally 1)
  POTION: 64
  SPLASH_POTION: 64
  LINGERING_POTION: 64
  GLASS_BOTTLE: 64
  HONEY_BOTTLE: 64
  EXPERIENCE_BOTTLE: 64
  DRAGON_BREATH: 64

  # Buckets (normally 1)
  WATER_BUCKET: 64
  LAVA_BUCKET: 64
  MILK_BUCKET: 64
  POWDER_SNOW_BUCKET: 64
  AXOLOTL_BUCKET: 64
  TADPOLE_BUCKET: 64
  COD_BUCKET: 64
  SALMON_BUCKET: 64
  TROPICAL_FISH_BUCKET: 64
  PUFFERFISH_BUCKET: 64
  BUCKET: 64

  # Stews (normally 1)
  MUSHROOM_STEW: 64
  RABBIT_STEW: 64
  BEETROOT_SOUP: 64
  SUSPICIOUS_STEW: 64

  # Signs (normally 16)
  OAK_SIGN: 64
  BIRCH_SIGN: 64
  SPRUCE_SIGN: 64
  JUNGLE_SIGN: 64
  ACACIA_SIGN: 64
  DARK_OAK_SIGN: 64
  CRIMSON_SIGN: 64
  WARPED_SIGN: 64
  MANGROVE_SIGN: 64
  CHERRY_SIGN: 64
  BAMBOO_SIGN: 64
  OAK_HANGING_SIGN: 64
  BIRCH_HANGING_SIGN: 64
  SPRUCE_HANGING_SIGN: 64
  JUNGLE_HANGING_SIGN: 64
  ACACIA_HANGING_SIGN: 64
  DARK_OAK_HANGING_SIGN: 64
  CRIMSON_HANGING_SIGN: 64
  WARPED_HANGING_SIGN: 64
  MANGROVE_HANGING_SIGN: 64
  CHERRY_HANGING_SIGN: 64
  BAMBOO_HANGING_SIGN: 64

  # Banners (normally 16)
  WHITE_BANNER: 64
  ORANGE_BANNER: 64
  MAGENTA_BANNER: 64
  LIGHT_BLUE_BANNER: 64
  YELLOW_BANNER: 64
  LIME_BANNER: 64
  PINK_BANNER: 64
  GRAY_BANNER: 64
  LIGHT_GRAY_BANNER: 64
  CYAN_BANNER: 64
  PURPLE_BANNER: 64
  BLUE_BANNER: 64
  BROWN_BANNER: 64
  GREEN_BANNER: 64
  RED_BANNER: 64
  BLACK_BANNER: 64

  # Beds (normally 1)
  WHITE_BED: 64
  ORANGE_BED: 64
  MAGENTA_BED: 64
  LIGHT_BLUE_BED: 64
  YELLOW_BED: 64
  LIME_BED: 64
  PINK_BED: 64
  GRAY_BED: 64
  LIGHT_GRAY_BED: 64
  CYAN_BED: 64
  PURPLE_BED: 64
  BLUE_BED: 64
  BROWN_BED: 64
  GREEN_BED: 64
  RED_BED: 64
  BLACK_BED: 64

  # Shulker Boxes (normally 1) - CRITICAL!
  SHULKER_BOX: 64
  WHITE_SHULKER_BOX: 64
  ORANGE_SHULKER_BOX: 64
  MAGENTA_SHULKER_BOX: 64
  LIGHT_BLUE_SHULKER_BOX: 64
  YELLOW_SHULKER_BOX: 64
  LIME_SHULKER_BOX: 64
  PINK_SHULKER_BOX: 64
  GRAY_SHULKER_BOX: 64
  LIGHT_GRAY_SHULKER_BOX: 64
  CYAN_SHULKER_BOX: 64
  PURPLE_SHULKER_BOX: 64
  BLUE_SHULKER_BOX: 64
  BROWN_SHULKER_BOX: 64
  GREEN_SHULKER_BOX: 64
  RED_SHULKER_BOX: 64
  BLACK_SHULKER_BOX: 64

  # Minecarts (normally 1)
  MINECART: 64
  CHEST_MINECART: 64
  FURNACE_MINECART: 64
  TNT_MINECART: 64
  HOPPER_MINECART: 64
  COMMAND_BLOCK_MINECART: 64

  # Boats (normally 1)
  OAK_BOAT: 64
  BIRCH_BOAT: 64
  SPRUCE_BOAT: 64
  JUNGLE_BOAT: 64
  ACACIA_BOAT: 64
  DARK_OAK_BOAT: 64
  MANGROVE_BOAT: 64
  CHERRY_BOAT: 64
  BAMBOO_RAFT: 64
  OAK_CHEST_BOAT: 64
  BIRCH_CHEST_BOAT: 64
  SPRUCE_CHEST_BOAT: 64
  JUNGLE_CHEST_BOAT: 64
  ACACIA_CHEST_BOAT: 64
  DARK_OAK_CHEST_BOAT: 64
  MANGROVE_CHEST_BOAT: 64
  CHERRY_CHEST_BOAT: 64
  BAMBOO_CHEST_RAFT: 64

  # Armor Stands (normally 16)
  ARMOR_STAND: 64

  # Cakes (normally 1)
  CAKE: 64

  # Cauldrons (normally 1)
  CAULDRON: 64
  LAVA_CAULDRON: 64
  WATER_CAULDRON: 64
  POWDER_SNOW_CAULDRON: 64

  # Doors (normally 1)
  OAK_DOOR: 64
  BIRCH_DOOR: 64
  SPRUCE_DOOR: 64
  JUNGLE_DOOR: 64
  ACACIA_DOOR: 64
  DARK_OAK_DOOR: 64
  CRIMSON_DOOR: 64
  WARPED_DOOR: 64
  MANGROVE_DOOR: 64
  CHERRY_DOOR: 64
  BAMBOO_DOOR: 64
  IRON_DOOR: 64

  # Heads (normally 1)
  PLAYER_HEAD: 64
  ZOMBIE_HEAD: 64
  SKELETON_SKULL: 64
  WITHER_SKELETON_SKULL: 64
  CREEPER_HEAD: 64
  DRAGON_HEAD: 64
  PIGLIN_HEAD: 64

  # Music Discs (normally 1)
  MUSIC_DISC_13: 64
  MUSIC_DISC_CAT: 64
  MUSIC_DISC_BLOCKS: 64
  MUSIC_DISC_CHIRP: 64
  MUSIC_DISC_FAR: 64
  MUSIC_DISC_MALL: 64
  MUSIC_DISC_MELLOHI: 64
  MUSIC_DISC_STAL: 64
  MUSIC_DISC_STRAD: 64
  MUSIC_DISC_WARD: 64
  MUSIC_DISC_11: 64
  MUSIC_DISC_WAIT: 64
  MUSIC_DISC_OTHERSIDE: 64
  MUSIC_DISC_5: 64
  MUSIC_DISC_PIGSTEP: 64
  MUSIC_DISC_RELIC: 64

  # Books (normally 1)
  ENCHANTED_BOOK: 64
  WRITABLE_BOOK: 64
  WRITTEN_BOOK: 64
  KNOWLEDGE_BOOK: 64

  # Horse Armor (normally 1)
  SADDLE: 64
  IRON_HORSE_ARMOR: 64
  GOLDEN_HORSE_ARMOR: 64
  DIAMOND_HORSE_ARMOR: 64
  LEATHER_HORSE_ARMOR: 64

  # Special Items (normally 1)
  TOTEM_OF_UNDYING: 64
  RECOVERY_COMPASS: 64
  COMPASS: 64
  CLOCK: 64
  GOAT_HORN: 64
  DECORATED_POT: 64

  # ========== TOOLS (normally 1) ==========
  DIAMOND_SWORD: 64
  DIAMOND_PICKAXE: 64
  DIAMOND_AXE: 64
  DIAMOND_SHOVEL: 64
  DIAMOND_HOE: 64
  IRON_SWORD: 64
  IRON_PICKAXE: 64
  IRON_AXE: 64
  IRON_SHOVEL: 64
  IRON_HOE: 64
  GOLDEN_SWORD: 64
  GOLDEN_PICKAXE: 64
  GOLDEN_AXE: 64
  GOLDEN_SHOVEL: 64
  GOLDEN_HOE: 64
  STONE_SWORD: 64
  STONE_PICKAXE: 64
  STONE_AXE: 64
  STONE_SHOVEL: 64
  STONE_HOE: 64
  WOODEN_SWORD: 64
  WOODEN_PICKAXE: 64
  WOODEN_AXE: 64
  WOODEN_SHOVEL: 64
  WOODEN_HOE: 64
  NETHERITE_SWORD: 64
  NETHERITE_PICKAXE: 64
  NETHERITE_AXE: 64
  NETHERITE_SHOVEL: 64
  NETHERITE_HOE: 64
  BOW: 64
  CROSSBOW: 64
  TRIDENT: 64
  FISHING_ROD: 64
  CARROT_ON_A_STICK: 64
  WARPED_FUNGUS_ON_A_STICK: 64
  FLINT_AND_STEEL: 64
  SHEARS: 64
  SHIELD: 64

  # ========== ARMOR (normally 1) ==========
  DIAMOND_HELMET: 64
  DIAMOND_CHESTPLATE: 64
  DIAMOND_LEGGINGS: 64
  DIAMOND_BOOTS: 64
  IRON_HELMET: 64
  IRON_CHESTPLATE: 64
  IRON_LEGGINGS: 64
  IRON_BOOTS: 64
  GOLDEN_HELMET: 64
  GOLDEN_CHESTPLATE: 64
  GOLDEN_LEGGINGS: 64
  GOLDEN_BOOTS: 64
  NETHERITE_HELMET: 64
  NETHERITE_CHESTPLATE: 64
  NETHERITE_LEGGINGS: 64
  NETHERITE_BOOTS: 64
  LEATHER_HELMET: 64
  LEATHER_CHESTPLATE: 64
  LEATHER_LEGGINGS: 64
  LEATHER_BOOTS: 64
  CHAINMAIL_HELMET: 64
  CHAINMAIL_CHESTPLATE: 64
  CHAINMAIL_LEGGINGS: 64
  CHAINMAIL_BOOTS: 64
  TURTLE_HELMET: 64
  ELYTRA: 64
